version: 2

project_name: gmro

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gmro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/open-cli-collective/gmail-ro/cmd.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

# Linux packages (.deb and .rpm)
nfpms:
  - id: gmro
    package_name: gmro
    vendor: Open CLI Collective
    homepage: https://github.com/open-cli-collective/gmail-ro
    maintainer: Open CLI Collective <https://github.com/open-cli-collective>
    description: Read-only command-line interface for Gmail
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/gmro/LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^Merge pull request"
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Other'
      order: 999
